import os

configfile: "config.yaml"

SAMPLES = list(config["samples"].keys())
OUTDIR = config["output"]["dir"]

include: "rules/qc_fastp.smk"
include: "rules/align_star.smk"
include: "rules/bam_post.smk"
include: "rules/featurecount.smk"
include: "rules/ciri3.smk"

rule all:
    input:
        # fastp sample-level QC
        expand(f"{OUTDIR}/qc/fastp/{{sample}}/fastp.html", sample=SAMPLES),
        expand(f"{OUTDIR}/qc/fastp/{{sample}}/fastp.json", sample=SAMPLES),

        # STAR outputs and MAPQ-filtered BAM
        expand(f"{OUTDIR}/star/{{sample}}/{{sample}}.Log.final.out", sample=SAMPLES),
        expand(f"{OUTDIR}/star/{{sample}}/{{sample}}.SJ.out.tab", sample=SAMPLES),
        expand(f"{OUTDIR}/star/{{sample}}/{{sample}}.unique.mapq11.sorted.bam", sample=SAMPLES),
        expand(f"{OUTDIR}/star/{{sample}}/{{sample}}.unique.mapq11.sorted.bam.bai", sample=SAMPLES),

        # featureCounts + CIRI3
        f"{OUTDIR}/featurecount/totalRNA.counts.txt",
        f"{OUTDIR}/ciri3/all_samples.ciri3",
        f"{OUTDIR}/ciri3/all_samples.ciri3.BSJ_Matrix",
        f"{OUTDIR}/ciri3/all_samples.ciri3.FSJ_Matrix",

        # summary QC
        f"{OUTDIR}/qc/multiqc/multiqc_report.html"
