threads:
  merge_fastq: 2
  fastp: 8
  star: 16
  bwa: 16
  samtools_index: 8
  samtools_view: 8
  featurecounts: 8
  faidx: 2
  homer: 8
  splicing_stats: 2

reference:
  star_index: "/path/to/reference/star_index"
  fasta: "/path/to/reference/genome.fa"
  bwa_indexed_fasta: "/path/to/reference/genome.fa"
  gtf: "/path/to/reference/annotation.gtf"

samples:
  "sample_A":
    R1:
      - "/path/to/fastq/sample_a_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_a_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_a_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_a_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_a_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_a_rep3_r2.fastq.gz"

  "sample_B":
    R1:
      - "/path/to/fastq/sample_b_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_b_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_b_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_b_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_b_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_b_rep3_r2.fastq.gz"

  "sample_C":
    R1:
      - "/path/to/fastq/sample_c_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_c_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_c_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_c_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_c_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_c_rep3_r2.fastq.gz"

  "sample_D":
    R1:
      - "/path/to/fastq/sample_d_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_d_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_d_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_d_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_d_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_d_rep3_r2.fastq.gz"

  "sample_E":
    R1:
      - "/path/to/fastq/sample_e_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_e_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_e_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_e_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_e_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_e_rep3_r2.fastq.gz"

  "sample_F":
    R1:
      - "/path/to/fastq/sample_f_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_f_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_f_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_f_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_f_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_f_rep3_r2.fastq.gz"

  "sample_G":
    R1:
      - "/path/to/fastq/sample_g_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_g_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_g_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_g_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_g_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_g_rep3_r2.fastq.gz"

  "sample_H":
    R1:
      - "/path/to/fastq/sample_h_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_h_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_h_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_h_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_h_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_h_rep3_r2.fastq.gz"

  "sample_I":
    R1:
      - "/path/to/fastq/sample_i_rep1_r1.fastq.gz"
      - "/path/to/fastq/sample_i_rep2_r1.fastq.gz"
      - "/path/to/fastq/sample_i_rep3_r1.fastq.gz"
    R2:
      - "/path/to/fastq/sample_i_rep1_r2.fastq.gz"
      - "/path/to/fastq/sample_i_rep2_r2.fastq.gz"
      - "/path/to/fastq/sample_i_rep3_r2.fastq.gz"

fastp:
  dedup_adapter:
    dedup: true

ciri3:
  jar: "/path/to/tools/CIRI3_Java_18.0.1.jar"
  Ma: 1
  W: 1

motif:
  enabled: true
  flank: 30
  weight_mode: "sum"
  homer_len: "8,10,12"

output:
  dir: "results"
  keep_bam: false

deg:
  enabled: false
  min_total_count: 10
  min_samples_detected: 2
  padj_cutoff: 0.05
  lfc_cutoff: 1.0
  groups:
    "condition X":
      - "sample_A"
      - "sample_B"
      - "sample_C"
    "condition Y":
      - "sample_D"
      - "sample_E"
      - "sample_F"
    "condition Z":
      - "sample_G"
      - "sample_H"
      - "sample_I"

ciri3_de:
  enabled: true
  run_de_bsj: true
  run_de_ratio: true
  run_de_relative: true
  outdir: "results/deg/ciri3"
  gene_expression_from_featurecounts: true
  comparisons:
    "condition_Y_vs_condition_X":
      case:
        - "sample_D"
        - "sample_E"
        - "sample_F"
      control:
        - "sample_A"
        - "sample_B"
        - "sample_C"

    "condition_Z_vs_condition_Y":
      case:
        - "sample_G"
        - "sample_H"
        - "sample_I"
      control:
        - "sample_D"
        - "sample_E"
        - "sample_F"

    "condition_Z_vs_condition_X":
      case:
        - "sample_G"
        - "sample_H"
        - "sample_I"
      control:
        - "sample_A"
        - "sample_B"
        - "sample_C"
